tproxy-port: 0
mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: warning
ipv6: false
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: ../dashboard/dist
tcp-concurrent: true
interface-name: ""
enable-process: false
geodata-loader: memconservative
# routing-mark: 233
inbound-tfo: true
secret: ""
geox-url: {mmdb: "", geoip: "https://github.com/v2fly/geoip/raw/release/geoip-only-cn-private.dat", geosite: "https://github.com/taamarin/v2ray-rules-dat/raw/release/GeoSite.dat"}
profile:
  store-selected: true
  store-fake-ip: false
experimental: {sniff-tls-sni: true, fingerprint: ""}
sniffer:
  enable: false
  sniffing: [tls, http]
  force-domain:
    - '+'
  skip-domain:
    - '+.google.com'
  port-whitelist: [443, 80]
  force-dns-mapping: true
  parse-pure-ip: true
hosts: {"cacerts.digicert.com": "104.21.21.147", "ota.googlezip.net": "127.0.0.1", "ota-cache1.googlezip.net": "127.0.0.1", "ota-cache2.googlezip.net": "127.0.0.1"}
tun:
  enable: true
  device: tun0
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict_route: false
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  default-nameserver:
    - 'tls://8.8.8.8' # Google
    - 'tcp://1.0.0.1' # Cloudflare
    - 'tcp://112.215.230.254:853#REJECT'
  listen: "0.0.0.0:1053"
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: "28.0.0.1/8"
  fake-ip-filter: ["*.local", "*.localhost"]
  nameserver:
    - 'https://1.1.1.1' # Cloudflare
    - 'https://8.8.8.8' # Google
  fallback:
    - 'tcp://1.0.0.1' # Cloudflare
    - 'tcp://8.8.4.4' # Google
    - 'tcp://9.9.9.9' # Quad9
  fallback-filter:
    geoip: false
    geoip-code: "ID"
    geosite: []
    ipcidr: [0.0.0.0/8, 10.0.0.0/8]
    domain: ['+.google.com', '+.youtube.com']
proxies:
proxy-groups:
  - name: "llycoris"
    type: select
    use: [
        🌸,🌼
    ]
  - name: "✘ has been banned" 
    type: select
    proxies: [
        REJECT,DIRECT
    ]
proxy-providers:
  🌸:
    type: file
    path: ./assets/llycoris.list
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  🌼:
    type: file
    path: ./assets/llycoris1.list
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
rules:
  - DOMAIN-SUFFIX,googlesyndication.com,llycoris
  - AND,((GEOSITE,YOUTUBE),(NETWORK,UDP)),REJECT
  - AND,((DST-PORT,5228-5230),(NETWORK,TCP)),DIRECT
  - GEOSITE,CATEGORY-ADS-ALL,✘ has been banned
  - IP-CIDR,198.18.0.1/16,DIRECT,no-resolve
  - IP-CIDR,127.0.0.1/32,DIRECT,no-resolve
  - MATCH,llycoris